# Generated by Django 3.2.2 on 2021-05-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='login')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
            ],
        ),
    ]
