# Generated by Django 3.2.2 on 2021-05-17 20:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usd_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255, null=True)),
                ('notes', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('teacher', models.CharField(max_length=255, null=True)),
                ('contact', models.CharField(max_length=255, null=True)),
                ('office_days', models.CharField(max_length=255, null=True)),
                ('lesson_link', models.CharField(max_length=255, null=True)),
                ('lesson_type', models.CharField(max_length=255, null=True)),
                ('when', models.CharField(max_length=255, null=True)),
                ('building', models.CharField(max_length=255, null=True)),
                ('room', models.CharField(max_length=255, null=True)),
                ('etcs', models.IntegerField(null=True)),
                ('info', models.CharField(max_length=4096, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='last_login',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='account',
            name='login',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('building', models.CharField(max_length=255, null=True)),
                ('teacher', models.CharField(max_length=255, null=True)),
                ('room', models.CharField(max_length=255, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usd_rest_api.group')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usd_rest_api.account')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usd_rest_api.group')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(to='usd_rest_api.Group'),
        ),
    ]
