# Generated by Django 3.2.2 on 2021-05-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usd_rest_api', '0002_auto_20210517_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='etcs',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
