# Generated by Django 3.2.2 on 2021-05-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usd_rest_api', '0003_alter_group_etcs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='etcs',
        ),
        migrations.AddField(
            model_name='group',
            name='ects',
            field=models.IntegerField(null=True),
        ),
    ]
