# Generated by Django 3.2.2 on 2021-05-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usd_rest_api', '0004_auto_20210517_2307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Course',
        ),
    ]
