# Generated by Django 3.2.2 on 2021-05-30 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usd_rest_api', '0007_event_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('contact', models.CharField(max_length=255, null=True)),
                ('office_days', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='course',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='course',
            name='office_days',
        ),
        migrations.AddField(
            model_name='account',
            name='image_url',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usd_rest_api.teacher'),
        ),
    ]
