# Generated by Django 3.2.2 on 2021-05-30 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usd_rest_api', '0008_auto_20210530_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
    ]
