# Generated by Django 3.2.2 on 2021-05-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usd_rest_api', '0009_remove_lesson_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='when',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
